version: "3"
services:
  backend:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgresqldb
  postgresqldb:
    image: postgres
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=bank
    command: -p 5432
